export enum ErrorCode {
  API_ERROR = 'API_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  NOT_ALLOWED = 'NOT_ALLOWED',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  INVALID_COOKIE = 'INVALID_COOKIE',
}
