import Nav from '@/src/components/nav/Nav';
import NavWrapper from '@/src/components/nav/NavBarWrapper';
import { dir } from 'i18next';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { FunctionComponent, PropsWithChildren, ReactElement } from 'react';
import '../globals.css';
import '../i18n';
import Providers from '../providers';
import { serverLogout } from './actions';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  params: {
    locale: string;
  };
}

const RootLayout: FunctionComponent<PropsWithChildren<RootLayoutProps>> = ({
  children,
  params: { locale },
}): ReactElement => {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={'h-screen w-screen bg-background' + inter.className}>
        <Providers>
          <NavWrapper params={{ locale }}>
            <Nav params={{ locale }} serverLogout={serverLogout} />
          </NavWrapper>
          <div className="h-[calc(100vh-64px)] overflow-y-auto">{children}</div>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
