import Nav from '@/src/components/navbar/Navbar';
import { dir } from 'i18next';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import '../i18n';
import Providers from '../providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>): JSX.Element => {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={'h-screen w-screen bg-background' + inter.className}>
        <Providers>
          <Nav />
          <div className="h-[calc(100vh-64px)] overflow-y-auto">{children}</div>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
